#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading go..."

ynh_go_install

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$app_path" --full_replace

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "$app:www-data" "$install_dir"
#=================================================
ynh_script_progression "Upgrading..."

export GOPATH="$install_dir/go"
export GOCACHE="$install_dir/go/.cache"
export GO111MODULE=on

pushd "$app_path"
    ynh_hide_warnings ynh_exec_as_app go mod download
    ynh_hide_warnings ynh_exec_as_app go build -tags=jsoniter
popd

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add "$app" --description="IP address API" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
