#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

#=================================================
# BUILDING APP
#=================================================
#ynh_script_progression "Upgrading..."

#export GOPATH="$install_dir/go"
#export GOCACHE="$install_dir/go/.cache"
#export GO111MODULE=on

#pushd "$install_dir/go/src/github.com/georgyo/ifconfig.io"
#    ynh_hide_warnings ynh_exec_as_app go mod download
#    ynh_hide_warnings ynh_exec_as_app go build -tags=jsoniter
#popd

#mv $install_dir/go/src/github.com/georgyo/ifconfig.io/ifconfig.io $install_dir/ifconfig.io/

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app..."

pushd $install_dir
    ynh_hide_warnings ynh_exec_as_app CGO_ENABLED=0 go build -o $install_dir/ifconfig
popd

chmod +x "$install_dir/ifconfig"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

ynh_config_add_logrotate

yunohost service add "$app" --description="IP address API" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
